### ISSUE TITLE
Adding accordion to the FAQ Page

### ISSUE THREAD

**Issue by Lasitha64** [chiphackers/zscore-wiki#31]
**Doesn't work the accordion  styles properly in the FAQ page.**

				 <div class="ui styled accordion">
  <div class="active title">
    <i class="dropdown icon"></i>
    <h2>What we can do in zscore</h2>
  </div>
  <div class="active content">
<p>using zscore web site you will be able to attempt quizes, watch lectures and tutorials conduct by quality lecturers, Competative with other users in tests and zscore will help you to get good results in G.C.E. A/Ls </p>
  </div>
  <div class="title">
    <i class="dropdown icon"></i>
    <h2>How to try a quiz in zscore.lk</h2>
  </div>
  <div class="content">
   <p>To attempt a quiz in zscore you need to have a google account and need to sign in with a proper google account.Then you can attempt any quiz or test in zscore.</p>
  </div>
  <div class="title">
    <i class="dropdown icon"></i>
   <h2>How to attempt quizes without loging to a google account</h2>
  </div>
  <div class="content">
   <p>You can't do quizes or watch videos without creating a google account, all the benifits will be available after you sign in with google in zscore web page.</p>
  </div>
</div>

**Comment by udara28** [comment]
In order to accordion to work you need to attach jquery.js and semantic.js files (refer contact.html to see how this is done.)

Then you need to add the following script (This script should come after linking jquery and semantic)
```
<script>
      $(document).ready(function(){
                $('.ui.accordion').accordion();
       });
</script>
```

Let me know if this works

**Comment by Lasitha64** [comment]
Yes it's working thanks for the help
